export const EXIT_ANIMATION_DELAY = 1;
export const EXIT_ANIMATION_DELAY_TIMELINE = 1;

export const PARLLAX_OFFSET_DOWN = 20;
export const PARLLAX_OFFSET_UP = -PARLLAX_OFFSET_DOWN;

export const EDUCATION_ANIMATION_DURATION = 0.5;

export const BROWSER_ANIMATION_DURATION = 0.7;
